services:
  store_app_fe:
    image: store_app_fe:latest
    container_name: store_app_fe
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    env_file:
      - .env